In [ ]:
#UPLOAD TRAIN TEST VALIDATE

In [ ]:
#!unzip train.zip
#!unzip test.zip
#!unzip valid.zip

In [ ]:
#REMOVE RECURSIVE FOLDER
!rm -rf __MACOSX/

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as img
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Flatten,MaxPooling2D
from tensorflow.keras.optimizers import RMSprop
import os

In [ ]:
def f(n):
  v=[]
  for i in range(0,10):
    if(i == n):
      v.append(1)
    else:
      v.append(0)
  return v

In [ ]:
#TRAINING
Xtrain = []
Ytrain = []
for filename in os.listdir("train"):
  if filename[-3:] == "png":
    matrix=np.asarray(Image.open("train/"+filename))/255
    Xtrain.append(matrix)
    n = int(filename[0])
    Ytrain.append(f(n))
  
Xtrain=np.array(Xtrain)
Ytrain=np.array(Ytrain)

In [ ]:
#VALIDATION
Xval = []
Yval = []
for filename in os.listdir("valid"):
  if filename[-3:] == "png":
    matrix=np.asarray(Image.open("valid/"+filename))/255
    Xval.append(matrix)
    n = int(filename[0])
    Yval.append(f(n))
  
Xval=np.array(Xval)
Yval=np.array(Yval)

In [ ]:
#TESTING
Xtest = []
Ytest = []
for filename in os.listdir("test"):
  if filename[-3:] == "png":
    matrix=np.asarray(Image.open("test/"+filename))/255
    Xtest.append(matrix)
    n = int(filename[0])
    Ytest.append(n)
  
Xtest=np.array(Xtest)
Ytest=np.array(Ytest)

In [ ]:
model = Sequential()

In [ ]:
model.add(Conv2D(32,(3,3),activation="relu"))
model.add(Conv2D(32,(3,3),activation="relu"))
#2 3x3 filter
#NN is looking for features and is looking for basic 
#features like lines and shapes
#incease number of finer features
#eg facial features
model.add(MaxPooling2D(2,2))
#pooling laye help by making the images smaller. 
#MAX POOLING

In [ ]:
model.add(Conv2D(64,(3,3),activation="relu"))
model.add(Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))

In [ ]:
model.add(Conv2D(128,(3,3),activation="relu"))
model.add(Conv2D(128,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))

In [ ]:
#flatten the model
model.add(Flatten())

In [ ]:
#Hidden DENSE LAYER
model.add(Dense(128,activation="relu"))

In [ ]:
#10 because we have 10 classification
model.add(Dense(10,activation="softmax"))

In [ ]:
model.compile(
    loss = "categorical_crossentropy",
    optimizer = RMSprop(learning_rate= .001),
    metrics = ["accuracy"]
)

In [ ]:
model.fit(
    Xtrain,
    Ytrain,
    epochs = 500,
    validation_data =(Xval,Yval)
)

Epoch 1/500
63/63 [==============================] - 275s 4s/step - loss: 2.3234 - accuracy: 0.1035 - val_loss: 2.2998 - val_accuracy: 0.0800
Epoch 2/500
63/63 [==============================] - 272s 4s/step - loss: 2.3207 - accuracy: 0.1275 - val_loss: 2.2845 - val_accuracy: 0.1480
Epoch 3/500
63/63 [==============================] - 274s 4s/step - loss: 2.2155 - accuracy: 0.2060 - val_loss: 2.4524 - val_accuracy: 0.1520
Epoch 4/500
63/63 [==============================] - 280s 4s/step - loss: 1.8441 - accuracy: 0.3280 - val_loss: 1.9341 - val_accuracy: 0.2720
Epoch 5/500
63/63 [==============================] - 284s 5s/step - loss: 1.4214 - accuracy: 0.4550 - val_loss: 1.2331 - val_accuracy: 0.5400
Epoch 6/500
63/63 [==============================] - 274s 4s/step - loss: 1.1942 - accuracy: 0.5875 - val_loss: 1.1880 - val_accuracy: 0.5240
Epoch 7/500
63/63 [==============================] - 273s 4s/step - loss: 0.7980 - accuracy: 0.7065 - val_loss: 0.7184 - val_accuracy: 0.7400
Epoch 

KeyboardInterrupt: ignored

In [ ]:
m=model.predict(Xtest)
m

array([[1.8389367e-06, 3.8809085e-13, 1.1888819e-02, ..., 6.0521459e-09,
        1.7583983e-09, 1.4452586e-12],
       [3.4764584e-02, 8.1541740e-10, 9.6294373e-01, ..., 2.9921677e-04,
        2.3580119e-06, 2.5964388e-08],
       [1.2867989e-01, 1.4775267e-05, 1.8826234e-03, ..., 8.5090927e-05,
        1.9632529e-01, 1.6265774e-01],
       ...,
       [2.9863449e-04, 1.5475415e-09, 7.7878502e-03, ..., 9.2748245e-09,
        1.1608615e-07, 7.3973726e-12],
       [2.6426351e-01, 4.2849155e-09, 1.1149760e-02, ..., 8.4265566e-04,
        6.1915298e-03, 1.2198771e-01],
       [2.5261479e-04, 4.5061196e-10, 2.4397461e-06, ..., 9.9972898e-01,
        1.8095945e-12, 9.4842944e-06]], dtype=float32)

In [ ]:
#Prediction
Yhat=np.argmax(m,axis=1)
Yhat

array([4, 2, 6, 6, 8, 6, 1, 3, 4, 6, 0, 9, 4, 0, 7, 9, 7, 1, 2, 1, 9, 4,
       0, 6, 0, 2, 0, 8, 0, 4, 0, 3, 6, 7, 4, 4, 3, 1, 2, 1, 0, 0, 2, 9,
       7, 3, 8, 3, 6, 3, 0, 6, 0, 3, 8, 1, 9, 4, 0, 9, 0, 3, 8, 7, 4, 8,
       6, 1, 1, 3, 0, 2, 2, 8, 6, 3, 6, 3, 7, 0, 7, 6, 6, 3, 3, 8, 1, 4,
       8, 1, 7, 0, 4, 4, 0, 1, 0, 3, 3, 6, 0, 8, 8, 0, 4, 2, 1, 8, 8, 1,
       8, 6, 7, 2, 2, 1, 3, 2, 2, 8, 8, 2, 5, 0, 8, 0, 8, 7, 6, 1, 8, 6,
       1, 4, 6, 2, 2, 2, 8, 6, 4, 2, 1, 4, 4, 3, 0, 2, 0, 8, 0, 6, 9, 1,
       0, 6, 8, 8, 3, 6, 4, 2, 9, 1, 4, 9, 3, 3, 0, 1, 0, 0, 3, 4, 9, 6,
       4, 8, 8, 1, 3, 2, 0, 1, 4, 3, 0, 0, 3, 9, 8, 3, 8, 4, 8, 6, 3, 3,
       0, 6, 6, 4, 8, 4, 0, 2, 3, 3, 9, 8, 5, 0, 0, 0, 2, 7, 1, 0, 5, 9,
       0, 8, 0, 0, 3, 0, 8, 9, 0, 0, 5, 1, 0, 8, 1, 2, 0, 7, 9, 7, 9, 8,
       9, 9, 3, 7, 9, 4, 3, 7])

In [ ]:
Ytest

array([4, 2, 9, 6, 6, 6, 1, 3, 4, 8, 0, 9, 4, 0, 7, 8, 7, 1, 2, 1, 9, 4,
       3, 5, 2, 2, 9, 6, 0, 4, 0, 3, 6, 7, 2, 4, 6, 1, 2, 1, 0, 0, 4, 9,
       7, 2, 6, 8, 6, 6, 0, 9, 3, 9, 8, 1, 9, 4, 3, 8, 3, 3, 6, 7, 4, 8,
       5, 1, 1, 5, 0, 2, 2, 8, 5, 9, 6, 5, 7, 2, 7, 5, 6, 5, 8, 8, 1, 4,
       9, 1, 7, 7, 1, 4, 0, 1, 0, 9, 3, 6, 3, 9, 6, 0, 4, 2, 1, 5, 8, 1,
       6, 6, 7, 2, 2, 1, 8, 4, 2, 6, 8, 2, 5, 0, 8, 0, 6, 7, 5, 9, 6, 8,
       0, 4, 6, 7, 4, 2, 8, 6, 4, 2, 1, 4, 4, 8, 3, 2, 0, 6, 7, 6, 6, 1,
       3, 6, 8, 6, 9, 6, 4, 2, 9, 1, 4, 9, 8, 5, 0, 1, 0, 7, 3, 1, 9, 5,
       4, 5, 8, 4, 8, 2, 9, 1, 4, 3, 0, 0, 2, 5, 6, 2, 0, 4, 8, 6, 9, 8,
       3, 5, 6, 4, 6, 4, 8, 2, 8, 9, 8, 6, 5, 0, 3, 0, 2, 7, 1, 3, 5, 8,
       0, 8, 0, 0, 7, 0, 6, 9, 3, 3, 5, 1, 3, 8, 1, 2, 9, 7, 9, 7, 6, 8,
       9, 6, 9, 7, 6, 4, 3, 7])

In [ ]:
diff=Ytest-Yhat

In [ ]:
count=0
for x in diff:
  if x==0:
    count=count+1

In [ ]:
count

153

In [ ]:
count/250

0.612